"""add goal key

Revision ID: 3ef3f8649043
Revises: 77cb9e681515
Create Date: 2026-09-24 20:49:51.071231+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types are rendered fully qualified by autogenerate.
import polska.db.types  # noqa: F401

revision: str = "3ef3f8649043"
down_revision: str | None = "77cb9e681515"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("key", sa.String(length=64), nullable=False))
        batch_op.create_index("ix_goals_company_key", ["company_id", "key"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_index("ix_goals_company_key")
        batch_op.drop_column("key")

    # ### end Alembic commands ###
