"""initial schema

Revision ID: 77cb9e681515
Revises:
Create Date: 2026-09-24 19:29:41.628300+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types are rendered fully qualified by autogenerate.
import polska.db.types  # noqa: F401

revision: str = "77cb9e681515"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("profile_path", sa.String(length=500), nullable=False),
        sa.Column("profile_hash", sa.String(length=64), nullable=False),
        sa.Column("profile", sa.JSON(), nullable=False),
        sa.Column("idea", sa.Text(), nullable=False),
        sa.Column("brand_voice", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", polska.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", polska.db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_companies_active"), ["active"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_companies_profile_hash"), ["profile_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_companies_slug"), ["slug"], unique=True)

    op.create_table(
        "activity_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "COMPANY_LOADED",
                "GOAL_CREATED",
                "GOAL_UPDATED",
                "PLAN_STARTED",
                "PLAN_COMPLETED",
                "TASK_ENQUEUED",
                "TASK_DEDUPED",
                "TASK_STATE_CHANGED",
                "RUN_STARTED",
                "RUN_FINISHED",
                "ACTION_PROPOSED",
                "ACTION_EXECUTED",
                "APPROVAL_DECIDED",
                "BUDGET_HALT",
                "BUDGET_RESUMED",
                "SCHEDULER_TICK",
                "ERROR",
                name="activitykind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("approval_id", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", polska.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_activity_company_created", ["company_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_approval_id"), ["approval_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_activity_events_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_activity_events_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_activity_events_task_id"), ["task_id"], unique=False)
        batch_op.create_index("ix_activity_kind_created", ["kind", "created_at"], unique=False)

    op.create_table(
        "budget_halts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column(
            "scope",
            sa.Enum("RUN", "DAY", "COMPANY", name="budgetscope", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("limit_name", sa.String(length=80), nullable=False),
        sa.Column("limit_value", sa.Float(), nullable=False),
        sa.Column("observed_value", sa.Float(), nullable=False),
        sa.Column("period_key", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", polska.db.types.UTCDateTime(), nullable=False),
        sa.Column("cleared_at", polska.db.types.UTCDateTime(), nullable=True),
        sa.Column("cleared_by", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("budget_halts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_budget_halts_company_cleared", ["company_id", "cleared_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budget_halts_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budget_halts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budget_halts_period_key"), ["period_key"], unique=False
        )

    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metric", sa.String(length=120), nullable=False),
        sa.Column("target_value", sa.Float(), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ACHIEVED",
                "PAUSED",
                "ABANDONED",
                name="goalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("due_date", polska.db.types.UTCDateTime(), nullable=True),
        sa.Column("achieved_at", polska.db.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", polska.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", polska.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_goals_company_id"), ["company_id"], unique=False)
        batch_op.create_index("ix_goals_company_status", ["company_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_goals_status"), ["status"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "ENGINEERING",
                "MARKETING",
                "SUPPORT",
                "RESEARCH",
                name="tasktype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "AWAITING_APPROVAL",
                "DONE",
                "FAILED",
                "ABANDONED",
                name="taskstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("dedup_note", sa.Text(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", polska.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", polska.db.types.UTCDateTime(), nullable=False),
        sa.Column("started_at", polska.db.types.UTCDateTime(), nullable=True),
        sa.Column("finished_at", polska.db.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("ix_tasks_company_dedup", ["company_id", "dedup_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_company_id"), ["company_id"], unique=False)
        batch_op.create_index("ix_tasks_company_state", ["company_id", "state"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_dedup_key"), ["dedup_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_goal_id"), ["goal_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_state"), ["state"], unique=False)
        batch_op.create_index("ix_tasks_state_created", ["state", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_type"), ["type"], unique=False)

    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column(
            "agent",
            sa.Enum(
                "PLANNER",
                "DEDUP_JUDGE",
                "ENGINEER",
                "MARKETER",
                "SUPPORT",
                "ANALYST",
                name="agentname",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("raw_output", sa.Text(), nullable=True),
        sa.Column("tools_called", sa.JSON(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_creation_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("cost_gbp", sa.Float(), nullable=False),
        sa.Column("fx_rate", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "TIMED_OUT",
                "BUDGET_BLOCKED",
                "INVALID_OUTPUT",
                name="runstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("started_at", polska.db.types.UTCDateTime(), nullable=False),
        sa.Column("finished_at", polska.db.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_agent"), ["agent"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_company_id"), ["company_id"], unique=False)
        batch_op.create_index("ix_runs_company_started", ["company_id", "started_at"], unique=False)
        batch_op.create_index("ix_runs_company_status", ["company_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_started_at"), ["started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_task_id"), ["task_id"], unique=False)

    op.create_table(
        "approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("action_type", sa.String(length=80), nullable=False),
        sa.Column("adapter", sa.String(length=60), nullable=False),
        sa.Column(
            "reversibility",
            sa.Enum(
                "REVERSIBLE", "IRREVERSIBLE", name="reversibility", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("preview", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXECUTED",
                "EXECUTION_FAILED",
                "EXPIRED",
                "CANCELLED",
                name="approvalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("decided_by", sa.String(length=80), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("auto_approved", sa.Boolean(), nullable=False),
        sa.Column("execution_result", sa.JSON(), nullable=True),
        sa.Column("execution_error", sa.Text(), nullable=True),
        sa.Column("requested_at", polska.db.types.UTCDateTime(), nullable=False),
        sa.Column("decided_at", polska.db.types.UTCDateTime(), nullable=True),
        sa.Column("executed_at", polska.db.types.UTCDateTime(), nullable=True),
        sa.Column("expires_at", polska.db.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approvals_action_type"), ["action_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvals_company_id"), ["company_id"], unique=False)
        batch_op.create_index("ix_approvals_company_status", ["company_id", "status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_approvals_requested_at"), ["requested_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_approvals_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvals_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_approvals_status_requested", ["status", "requested_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_approvals_task_id"), ["task_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_task_id"))
        batch_op.drop_index("ix_approvals_status_requested")
        batch_op.drop_index(batch_op.f("ix_approvals_status"))
        batch_op.drop_index(batch_op.f("ix_approvals_run_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_requested_at"))
        batch_op.drop_index("ix_approvals_company_status")
        batch_op.drop_index(batch_op.f("ix_approvals_company_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_action_type"))

    op.drop_table("approvals")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_task_id"))
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_started_at"))
        batch_op.drop_index("ix_runs_company_status")
        batch_op.drop_index("ix_runs_company_started")
        batch_op.drop_index(batch_op.f("ix_runs_company_id"))
        batch_op.drop_index(batch_op.f("ix_runs_agent"))

    op.drop_table("runs")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_type"))
        batch_op.drop_index("ix_tasks_state_created")
        batch_op.drop_index(batch_op.f("ix_tasks_state"))
        batch_op.drop_index(batch_op.f("ix_tasks_goal_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_dedup_key"))
        batch_op.drop_index("ix_tasks_company_state")
        batch_op.drop_index(batch_op.f("ix_tasks_company_id"))
        batch_op.drop_index("ix_tasks_company_dedup")

    op.drop_table("tasks")
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_goals_status"))
        batch_op.drop_index("ix_goals_company_status")
        batch_op.drop_index(batch_op.f("ix_goals_company_id"))

    op.drop_table("goals")
    with op.batch_alter_table("budget_halts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_halts_period_key"))
        batch_op.drop_index(batch_op.f("ix_budget_halts_created_at"))
        batch_op.drop_index(batch_op.f("ix_budget_halts_company_id"))
        batch_op.drop_index("ix_budget_halts_company_cleared")

    op.drop_table("budget_halts")
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.drop_index("ix_activity_kind_created")
        batch_op.drop_index(batch_op.f("ix_activity_events_task_id"))
        batch_op.drop_index(batch_op.f("ix_activity_events_run_id"))
        batch_op.drop_index(batch_op.f("ix_activity_events_kind"))
        batch_op.drop_index(batch_op.f("ix_activity_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_activity_events_company_id"))
        batch_op.drop_index(batch_op.f("ix_activity_events_approval_id"))
        batch_op.drop_index("ix_activity_company_created")

    op.drop_table("activity_events")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_slug"))
        batch_op.drop_index(batch_op.f("ix_companies_profile_hash"))
        batch_op.drop_index(batch_op.f("ix_companies_active"))

    op.drop_table("companies")
    # ### end Alembic commands ###
